jwt:
    secret: secret

spring:
    datasource:
        driver-class-name: org.h2.jdbcx.JdbcDataSource
        url: jdbc:h2:mem:ufo;DB_CLOSE_DELAY=-1
        name:
        username: 
        password:

logging:
    level:
        org.springframework: INFO
        ufo: DEBUG